# Pandas DataFrames & Indexing

## The Pandas Series Object

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### Series as generalized NumPy array

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

0.5

#### Series as specialized dictionary

In [9]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [10]:
population['California']

38332521

In [11]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

#### Constructing Series objects

In [12]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [13]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [14]:
pd.Series({2:'a', 1:'b', 3:'c'})

1    b
2    a
3    c
dtype: object

In [15]:
pd.Series({2:'a', 1:'b', 3:'c'}, index = [3,2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

#### DataFrame as a generalized NumPy array

In [16]:
area_dict = {'California': 423967,
                   'Texas': 695662,
                   'New York': 141297,
                   'Florida': 170312,
                   'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [17]:
states = pd.DataFrame({'population': population, 'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [18]:
states.index

Index([u'California', u'Florida', u'Illinois', u'New York', u'Texas'], dtype='object')

In [19]:
states.columns

Index([u'area', u'population'], dtype='object')

#### DataFrame as a specialized dictionary

In [20]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

#### Constructing DataFrame objects

In [23]:
# From a single Series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

In [24]:
# From a list of dicts
data = [{'a': i, 'b': 2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [25]:
# Pandas fills in missing dict keys
pd.DataFrame([{'a': 1, 'b': 2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [26]:
# From a dictionary of Series objects
pd.DataFrame({'population': population, 'area': area})

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [28]:
# From a 2D NumPy array
pd.DataFrame(np.random.rand(3,2), columns=['foo','bar'], index=['a','b','c'])

foo       bar
a  0.625157  0.860505
b  0.276761  0.808993
c  0.395421  0.381889

In [29]:
# From a NumPy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B','f8')])
A

array([(0,  0.), (0,  0.), (0,  0.)], 
      dtype=[('A', '<i8'), ('B', '<f8')])

In [30]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [31]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as immutable array

In [32]:
ind[1]

3

In [33]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [34]:
print ind.size, ind.shape, ind.ndim, ind.dtype

5 (5,) 1 int64


In [35]:
# indices are immutable. should return error
ind[1] = 0

TypeError: Index does not support mutable operations

#### Index as ordered set

In [36]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [37]:
indA & indB # instersection

Int64Index([3, 5, 7], dtype='int64')

In [38]:
indA | indB # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [39]:
indA ^ indB # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection
### Data Selection in Series
#### Series as dictionary

In [40]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [41]:
data['b']

0.5

In [42]:
'a' in data

True

In [43]:
data.keys()

Index([u'a', u'b', u'c', u'd'], dtype='object')

In [45]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series as one-dimensional array

In [46]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [47]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [48]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [49]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

#### Indexers: loc, iloc, ix

In [50]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [51]:
# explicit indext when indexing
data[1]

'a'

In [52]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [53]:
data.loc[1]

'a'

In [54]:
data.loc[1:3]

1    a
3    b
dtype: object

In [55]:
# iloc = index location. iloc of 1 is the 2nd item
data.iloc[1]

'b'

In [56]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame
#### DataFrame as a dictionary

In [57]:
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [68]:
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [69]:
data = pd.DataFrame({'area': area, 'population': population})
data

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [70]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [71]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [72]:
data.area is data['area']

True

In [73]:
data['density'] = data['population'] / data['area']
data

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

#### DataFrame as 2D array

In [74]:
data.values

array([[  4.23967000e+05,   3.83325210e+07,   9.04139261e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

In [75]:
# Transpose
data.T

California       Florida      Illinois      New York  \
area        4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05   
population  3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07   
density     9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02   

                   Texas  
area        6.956620e+05  
population  2.644819e+07  
density     3.801874e+01

In [76]:
data.values[0]

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

In [77]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [78]:
data.iloc[:3, :2]

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135

In [79]:
data.loc[:'Illinois', :'population']

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135

In [80]:
data.ix[:3, :'population']

/Volumes/RobStorage/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135

In [81]:
# Show the pop and density of cities with density > 100
data.loc[data.density > 100, ['population', 'density']]

population     density
Florida     19552860  114.806121
New York    19651127  139.076746

In [82]:
# change value in 1st row, 3rd column
data.iloc[0, 2] = 90
data

area  population     density
California  423967    38332521   90.000000
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

#### Additional indexing conventions

In [83]:
data['Florida':'Illinois']

area  population     density
Florida   170312    19552860  114.806121
Illinois  149995    12882135   85.883763

In [84]:
data[1:3]

area  population     density
Florida   170312    19552860  114.806121
Illinois  149995    12882135   85.883763

In [85]:
data[data.density > 100]

area  population     density
Florida   170312    19552860  114.806121
New York  141297    19651127  139.076746